graphql:
  spqr:
    gui:
      enabled: true
      target-endpoint: /graphql
      target-ws-endpoint: /ws
server:
  port: 3001
spring:
  data:
    mongodb:
      auto-index-creation: true
cookie:
  name: JWTAuth
  jwt:
    secret: TaskMasterJWT
